### ISSUE TITLE
SoundEffect vol_start/vol_end parameters and attributes accepts values up to 2492

### ISSUE THREAD

**Issue by microbit-carlos** [microbit-foundation/micropython-microbit-v2#129]
Up to value 2492 works, although anything above 255 (the max value) sounds as loud:
```python
>>> audio.SoundEffect(vol_start=2492, vol_end=2492)
SoundEffect(500, 2500, 500, 2492, 2492, 3, 0, 18)
>>> audio.SoundEffect().vol_start = 2492
>>> audio.SoundEffect().vol_end = 2492
>>> 
```

2493 starts to throw exceptions indicating the max value is 9999.
```python
>>> audio.SoundEffect(vol_start=2493)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: maximum value is 9999
>>> audio.SoundEffect(vol_end=2493)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: maximum value is 9999
>>> audio.SoundEffect().vol_start = 2493
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: maximum value is 9999
>>> audio.SoundEffect().vol_end = 2493
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: maximum value is 9999
>>> 
```

**Comment by dpgeorge** [comment]
Fixed by de3813848f09ba954b56b11b7d4a08a572a536e3
